from fsnn_classifiers.components.decoding.diehl_decoder import DiehlDecoder
from fsnn_classifiers.components.decoding.own_rate_decoder import OwnRateDecoder
from fsnn_classifiers.components.decoding.own_rate_population_decoder import OwnRatePopulationDecoder
from fsnn_classifiers.components.decoding.multi_decoder import MultiDecoder